version: '3'
services:
  db:
    image: getjv/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - C:\Projetos\Projeto_Avaliativo\liket\bases\mysql:/var/lib/mysql
  web:
    image: brancosmith/ubuntu
    ports:
      - "80:80"
    volumes:
      - C:\Projetos\Projeto_Avaliativo\liket:/var/www/html
    links:
     - db

     